/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:c41527ab-b0f0-413a-8ab8-915541e1e07c",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_5C3Vvm6yz",
    "aws_user_pools_web_client_id": "1ppnb5v2uc40uvnsk70r8aa4ph",
    "oauth": {}
};


export default awsmobile;
